name: sonarqube-hybrid-plugin-typescript
kind: workflow 
apiVersion: automation.cloudbees.io/v1alpha1

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: 30 21 * * 1-5
    
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  sonar-hybrid-scan:
    steps:        
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1

      - name: Setup sonarqube explicit scanner
        uses: cloudbees-io/sonarqube-plugin@v1
        with:
          url: 'https://sonarqube.saas-preprod.beescloud.com'
          username: ${{ secrets.SONARQUBE_USERNAME }}
          password: ${{ secrets.SONARQUBE_PASSWORD }}
          ref: main
          
